apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      restartPolicy: Never
      containers:
        - name: db-migration
          image: 'uitdkhpacr2026.azurecr.io/db-migration:7341e016008deef8ba0086d75810aec6ad80afb4'
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: uit-dkhp-secret
                  key: DATABASE_URL
            - name: RUN_SEED
              value: "true"
