apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: uitdkhpacr2026.azurecr.io/course-service:492e5ca5160e9dbec0c5f3677c333b6c755b0008
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - name: http
          containerPort: 3002
        envFrom:
        - configMapRef:
            name: uit-dkhp-config
        - secretRef:
            name: uit-dkhp-secret
        env:
        - name: PORT
          value: "3002"
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  labels:
    app: course-service
spec:
  ports:
  - name: http
    port: 3002
    targetPort: 3002
  selector:
    app: course-service
