apiVersion: v1
kind: Secret
metadata:
  name: uit-dkhp-secret
  namespace: default
type: Opaque
stringData:  # TODO: Thay thế YOUR_DB_HOST bằng fqdn của database từ Terraform, và YOUR_DB_PASSWORD bằng mật khẩu thực tế
  DATABASE_URL: "postgresql://pgadmin:12345678@uit-dkhp-pg-server.postgres.database.azure.com:5432/uit_dkhp?sslmode=require"
  JWT_SECRET: "change-me-in-production"
  JWT_EXPIRES_IN: "7d"
  MAILTRAP_USER: "your-mailtrap-user"
  MAILTRAP_PASS: "your-mailtrap-pass"
